'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApRadar3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar_361() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar_361", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ApRadar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApRadar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BackVista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackVista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BarBack_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarBack_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close16x16_Hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close16x16_Hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Extract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Extract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ffxiah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ffxiah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filterbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filterbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_rare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_rare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MappedRadar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MappedRadar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RadarIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RadarIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rssNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rssNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Skull_Bones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skull_Bones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trans_Wind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trans_Wind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
