'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoHide() As Boolean
            Get
                Return CType(Me("AutoHide"),Boolean)
            End Get
            Set
                Me("AutoHide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wiki")>  _
        Public Property SearchProvider() As String
            Get
                Return CType(Me("SearchProvider"),String)
            End Get
            Set
                Me("SearchProvider") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2008-10-11")>  _
        Public Property MapPackVersion() As Date
            Get
                Return CType(Me("MapPackVersion"),Date)
            End Get
            Set
                Me("MapPackVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2009-02-12")>  _
        Public Property MapIniVersion() As Date
            Get
                Return CType(Me("MapIniVersion"),Date)
            End Get
            Set
                Me("MapIniVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckVersionAtStartup() As Boolean
            Get
                Return CType(Me("CheckVersionAtStartup"),Boolean)
            End Get
            Set
                Me("CheckVersionAtStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeRequired() As Boolean
            Get
                Return CType(Me("UpgradeRequired"),Boolean)
            End Get
            Set
                Me("UpgradeRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckMapUpdates() As Boolean
            Get
                Return CType(Me("CheckMapUpdates"),Boolean)
            End Get
            Set
                Me("CheckMapUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckAppUpdates() As Boolean
            Get
                Return CType(Me("CheckAppUpdates"),Boolean)
            End Get
            Set
                Me("CheckAppUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SystemDefault")>  _
        Public Property TextRendering() As Global.System.Drawing.Text.TextRenderingHint
            Get
                Return CType(Me("TextRendering"),Global.System.Drawing.Text.TextRenderingHint)
            End Get
            Set
                Me("TextRendering") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HighSpeed")>  _
        Public Property SmoothingMode() As Global.System.Drawing.Drawing2D.SmoothingMode
            Get
                Return CType(Me("SmoothingMode"),Global.System.Drawing.Drawing2D.SmoothingMode)
            End Get
            Set
                Me("SmoothingMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HighSpeed")>  _
        Public Property CompositingQuality() As Global.System.Drawing.Drawing2D.CompositingQuality
            Get
                Return CType(Me("CompositingQuality"),Global.System.Drawing.Drawing2D.CompositingQuality)
            End Get
            Set
                Me("CompositingQuality") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pandemonium")>  _
        Public Property Server() As String
            Get
                Return CType(Me("Server"),String)
            End Get
            Set
                Me("Server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowPosition() As Boolean
            Get
                Return CType(Me("ShowPosition"),Boolean)
            End Get
            Set
                Me("ShowPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowZoneTimer() As Boolean
            Get
                Return CType(Me("ShowZoneTimer"),Boolean)
            End Get
            Set
                Me("ShowZoneTimer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowClock() As Boolean
            Get
                Return CType(Me("ShowClock"),Boolean)
            End Get
            Set
                Me("ShowClock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentTheme() As String
            Get
                Return CType(Me("CurrentTheme"),String)
            End Get
            Set
                Me("CurrentTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Primary")>  _
        Public Property Monitor() As String
            Get
                Return CType(Me("Monitor"),String)
            End Get
            Set
                Me("Monitor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoSaveRadarSettings() As Boolean
            Get
                Return CType(Me("AutoSaveRadarSettings"),Boolean)
            End Get
            Set
                Me("AutoSaveRadarSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MapOpen() As Boolean
            Get
                Return CType(Me("MapOpen"),Boolean)
            End Get
            Set
                Me("MapOpen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OverlayOpen() As Boolean
            Get
                Return CType(Me("OverlayOpen"),Boolean)
            End Get
            Set
                Me("OverlayOpen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CampingMode() As Boolean
            Get
                Return CType(Me("CampingMode"),Boolean)
            End Get
            Set
                Me("CampingMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowNews() As Boolean
            Get
                Return CType(Me("ShowNews"),Boolean)
            End Get
            Set
                Me("ShowNews") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Info")>  _
        Public Property Say() As Global.System.Drawing.Color
            Get
                Return CType(Me("Say"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Say") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightCoral")>  _
        Public Property Shout() As Global.System.Drawing.Color
            Get
                Return CType(Me("Shout"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Shout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Violet")>  _
        Public Property Tell() As Global.System.Drawing.Color
            Get
                Return CType(Me("Tell"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Tell") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property Emote() As Global.System.Drawing.Color
            Get
                Return CType(Me("Emote"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Emote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Arial, 9pt")>  _
        Public Property ChatFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("ChatFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("ChatFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FlashWindow() As Boolean
            Get
                Return CType(Me("FlashWindow"),Boolean)
            End Get
            Set
                Me("FlashWindow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HideAltTab() As Boolean
            Get
                Return CType(Me("HideAltTab"),Boolean)
            End Get
            Set
                Me("HideAltTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2009-01-01")>  _
        Public Property LastRSSDate() As Date
            Get
                Return CType(Me("LastRSSDate"),Date)
            End Get
            Set
                Me("LastRSSDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutomaticNewsUpdates() As Boolean
            Get
                Return CType(Me("AutomaticNewsUpdates"),Boolean)
            End Get
            Set
                Me("AutomaticNewsUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property NewsCheckInterval() As Integer
            Get
                Return CType(Me("NewsCheckInterval"),Integer)
            End Get
            Set
                Me("NewsCheckInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MaxNewsItems() As Integer
            Get
                Return CType(Me("MaxNewsItems"),Integer)
            End Get
            Set
                Me("MaxNewsItems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RemoteChatMessage() As Boolean
            Get
                Return CType(Me("RemoteChatMessage"),Boolean)
            End Get
            Set
                Me("RemoteChatMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartSpawnAlerts() As Boolean
            Get
                Return CType(Me("StartSpawnAlerts"),Boolean)
            End Get
            Set
                Me("StartSpawnAlerts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseAlertTimeout() As Boolean
            Get
                Return CType(Me("UseAlertTimeout"),Boolean)
            End Get
            Set
                Me("UseAlertTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Exclamation")>  _
        Public Property AlertSound() As String
            Get
                Return CType(Me("AlertSound"),String)
            End Get
            Set
                Me("AlertSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SupressToast() As Boolean
            Get
                Return CType(Me("SupressToast"),Boolean)
            End Get
            Set
                Me("SupressToast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowTracker() As Boolean
            Get
                Return CType(Me("ShowTracker"),Boolean)
            End Get
            Set
                Me("ShowTracker") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EnableOutOfRange() As Boolean
            Get
                Return CType(Me("EnableOutOfRange"),Boolean)
            End Get
            Set
                Me("EnableOutOfRange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PlayAlertOnSpawn() As Boolean
            Get
                Return CType(Me("PlayAlertOnSpawn"),Boolean)
            End Get
            Set
                Me("PlayAlertOnSpawn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property RefreshRate() As Integer
            Get
                Return CType(Me("RefreshRate"),Integer)
            End Get
            Set
                Me("RefreshRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckForBetaReleases() As Boolean
            Get
                Return CType(Me("CheckForBetaReleases"),Boolean)
            End Get
            Set
                Me("CheckForBetaReleases") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BetaRelease() As Boolean
            Get
                Return CType(Me("BetaRelease"),Boolean)
            End Get
            Set
                Me("BetaRelease") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ApRadar3.My.MySettings
            Get
                Return Global.ApRadar3.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
